### Scientific Computing: NumPy

NumPy (**Num**erical **Py**thon) is one of the most common packages used in Python. In fact, numerous computational packages that offer scientific capabilities utilize NumPy's array objects as a standard interface for data exchange. That's why understanding NumPy arrays and array-based computing principles is crucial. 

NumPy offers a vast array of efficient methods for creating and manipulating numerical data arrays. Unlike Python lists, which can accommodate various data types within a single list, NumPy arrays require homogeneity among their elements for efficient mathematical operations. Utilizing NumPy arrays provides advantages such as faster execution and reduced memory consumption compared to Python lists. With NumPy, data storage is optimized through the specification of data types, enhancing code optimization.

:::{.callout-note}
Documentation for this package is available at https://numpy.org/doc/stable/.
:::

To use NumPy in your code, you typically import it with the alias `np`

In [1]:
import numpy as np

#### Creating NumPy Arrays

Arrays serve as a fundamental data structure within the NumPy. They represent a grid of values containing information on raw data, element location, and interpretation. Elements share a common data type, known as the array dtype.

One method of initializing NumPy arrays involves using Python lists, with nested lists employed for two- or higher-dimensional data structures.

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
print("1D array:", a)

1D array: [1 2 3 4 5 6]


We can access the elements through indexing. 

In [3]:
a[0]

1

Arrays are N-Dimensional (that's why sometimes we refer to them as ndarray). That means that NumPy arrays will encompass vector (1-Dimensions), Matrices (2D) or tensors (3D and higher). We can get all the information of the array by checking its attributes. To create a 2D array, we can use nested lists:

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

Mathematically, we can think of this as a matrix with 2 rows and 4 columns, i.e.,

$$a=\begin{bmatrix}1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \end{bmatrix}$$

We can check its attributes to get more information about the array:

In [5]:
print('Dimensions/axes:', a.ndim)
print('Shape (size of array in each dimension):', a.shape)
print('Size (total number of elements):', a.size)
print('Number of bytes:', a.nbytes)
print('Data type:', a.dtype)
print('Item size (in bytes):', a.itemsize)

Dimensions/axes: 2
Shape (size of array in each dimension): (2, 4)
Size (total number of elements): 8
Number of bytes: 64
Data type: int64
Item size (in bytes): 8


We have already seen how to access elements in a 1D array. For 2D arrays, we can use two indices: the first for the row and the second for the column.

In [6]:
element = a[0, 2]  # Access the element in the first row and third column
print("Element at (0, 2):", element)

Element at (0, 2): 3


We can also use slicing to access subarrays. For example, to get the first two rows and the first three columns:

In [7]:
subarray = a[0:2, 0:3]
print("Subarray:\n", subarray)

Subarray:
 [[1 2 3]
 [5 6 7]]


We don't need to specify both indices all the time. For example, to get the first row, we can do

In [8]:
first_row = a[0, :]
print("First row:", first_row)

First row: [1 2 3 4]


or to get the second column

In [9]:
second_column = a[:, 1]
print("Second column:", second_column)

Second column: [2 6]


We can initialize arrays using different commands depending on our aim. For instance, the most straightforward case would be to pass a list to `np.array()` to create one: 

In [10]:
arr1 = np.array([5,6,7])
arr1

array([5, 6, 7])

However, sometimes we are more ambiguous and have no information on what our array contains. We just need to be able to initialize an array so that later on, our code, can update it. For this, we typically create arrays of the desired dimensions and fill them with zeros (`np.zeros()`), ones (`np.ones()`), with a given value (`np.full()`) or without initializing (`np.empty()`). 

:::{.callout-tip}
When working with large data, `np.empty()` can be faster and more efficient. Also, large arrays can take up most of your memory and, in those cases, carefully establishing the `dtype()` can help to manage memory more efficiently (i.e.,  choose 8 bits over 64 bits.)
:::

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

To create higher-dimensional arrays, we can pass a tuple representing the shape of the array:

In [13]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

This created a 3D array with 3 layers of matrices with 2 rows and 1 column. 


We can use `np.full()` to create an array of constant values that we specify in the `fill_value` option. 

In [14]:
np.full((2,2) , fill_value= 4)

array([[4, 4],
       [4, 4]])

`np.empty()` creates an array without initializing its values. The values in the array will be whatever is already present in the allocated memory, which can be random and unpredictable.

In [15]:
np.empty(2)

array([2.05833592e-312, 2.33419537e-312])

With `np.linspace()`, we can create arrays with evenly spaced values over a specified range. The syntax is `np.linspace(start, stop, num)`, where `start` is the starting value, `stop` is the ending value, and `num` is the number of evenly spaced values to generate.

In [16]:
np.linspace(0, 1, 5)  # Generates 5 evenly spaced values between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

`np.arange()` is another useful function to create arrays with evenly spaced values, similar to the built-in `range()` function but returning a NumPy array. The syntax is `np.arange(start, stop, step)`, where `start` is the starting value, `stop` is the ending value (exclusive), and `step` is the increment between each value.

In [17]:
np.arange(0, 10, 2)  # Generates values from 0 to 8 with a step of 2

array([0, 2, 4, 6, 8])

Note that both `np.linspace()` and `np.arange()` can be used to create sequences of numbers, but they differ in how you specify the spacing and the number of elements. In general, use `np.linspace()` when you want a specific number of evenly spaced values over a range, and use `np.arange()` when you want to specify the step size between values.

Sometimes, you might also need to create identity matrices, which are square matrices with ones on the diagonal and zeros elsewhere. You can use `np.eye()` to create an identity matrix of a specified size.

In [18]:
np.eye(3)  # Creates a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Or you might want to create diagonal matrices with specific values on the diagonal. You can use `np.diag()` for this purpose.

In [19]:
np.diag([1, 2, 3])  # Creates a diagonal matrix with 1, 2, 3 on the diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Finally, to create random arrays, NumPy provides several functions in the `np.random` module. For example, you can create an array of random floats between 0 and 1 using `np.random.rand()`, or an array of random integers within a specified range using `np.random.randint()`, or a normal distribution using `np.random.randn()`.

In [20]:
np.random.rand(2, 3)  # Creates a 2x3 array of random floats between 0 and 1

array([[0.02854967, 0.42667435, 0.58554677],
       [0.19140104, 0.82028622, 0.40383601]])

In [21]:
np.random.randint(0, 10, size=(2, 3))  # Creates a 2x3 array of random integers between 0 and 9

array([[3, 7, 2],
       [8, 8, 1]])

In [22]:
np.random.randn(2, 3)  # Creates a 2x3 array of random floats from a standard normal distribution

array([[-1.38212767,  0.00598517,  0.64093326],
       [ 1.79950684, -1.31887837, -0.9743646 ]])

:::{.callout-tip}
### Random Seed

When generating random numbers, it's often useful to set a random seed using `np.random.seed()`. This ensures that the sequence of random numbers generated is reproducible, meaning that you will get the same random numbers each time you run your code with the same seed. This is particularly important for debugging and sharing results.

:::


#### Managing Array Data

Arrays accept common operations like sorting, concatenating and finding unique elements. 

For instance, using the `sort()` method we can sort elements within an array. 

In [23]:
arr1 = np.array((10,2,5,3,50,0))
np.sort(arr1)

array([ 0,  2,  3,  5, 10, 50])

In multidimensional arrays, we can sort the elements of a given dimension by specifying the axis along which to sort. When axis=0, the operation collapses along the first dimension (rows in a 2D array), giving one result per column. When axis=1, it collapses along the second dimension (columns in a 2D array), giving one result per row.

In [24]:
mat1 = np.array([[1,2,3],[8,1,5]])
mat1

array([[1, 2, 3],
       [8, 1, 5]])

In [25]:
mat1.sort(axis=1)  # Sort along columns
mat1

array([[1, 2, 3],
       [1, 5, 8]])

Using `concatenate` we can join the elements of two arrays along an existing axis. 

In [26]:
arr1 = np.array((1,2,3))
arr2 = np.array((6,7,8))
np.concatenate((arr1,arr2))

array([1, 2, 3, 6, 7, 8])

Instead, if we want to concatenate along a new axis, we use `vstack()` and `hstack()` 

In [27]:
np.vstack((arr1,arr2))  # Vertical stack

array([[1, 2, 3],
       [6, 7, 8]])

In [28]:
np.hstack((arr1,arr2))  # Horizontal stack

array([1, 2, 3, 6, 7, 8])

It is also possible to reshape arrays. For instance, let's reshape the concatenation of `arr1` and `arr2` to 3 rows and 2 columns

In [29]:
arr_c = np.concatenate((arr1,arr2))
arr_c.reshape((3,2))

array([[1, 2],
       [3, 6],
       [7, 8]])

We can also perform aggregation functions over all elements, like finding the minimum, maximum, means, sum of elements and much more. 

In [30]:
print(arr1.min())
print(arr1.sum())
print(arr1.max())
print(arr1.mean())

1
6
3
2.0


This can also be done over a specific axis in multidimensional arrays. For example, let's create a 2D array and find the sum across rows and columns

In [31]:
mat2 = np.array([[1,2,3],[4,5,6]])
print(mat2.sum(axis=0))  # Sum along rows
print(mat2.sum(axis=1))  # Sum along columns

[5 7 9]
[ 6 15]


It is also possible to get only the unique elements of an array or to count how many elements are repeated. 

In [32]:
arr1 = np.array((1,2,3,3,1,1,5,6,7,8,11,11))
print(np.unique(arr1))
unq, count = np.unique(arr1, return_counts=True)
print("Unique elements:", unq)
print("Counts:", count)

[ 1  2  3  5  6  7  8 11]
Unique elements: [ 1  2  3  5  6  7  8 11]
Counts: [3 1 2 1 1 1 1 2]


Using `where()`, we can find the indices of elements that satisfy a given condition.

In [33]:
arr1 = np.array((10,15,20,25,30,35,40))
indices = np.where(arr1 > 25)
print("Indices of elements greater than 25:", indices)

Indices of elements greater than 25: (array([4, 5, 6]),)


We can also use boolean indexing to filter elements based on a condition.

In [34]:
filtered_elements = arr1[arr1 > 25]
print("Elements greater than 25:", filtered_elements)

Elements greater than 25: [30 35 40]


And we can replace elements that meet a condition using `np.where()`

In [35]:
new_arr = np.where(arr1 > 25, -1, arr1)  # Replace elements greater than 25 with -1
print("Array after replacement:", new_arr)

Array after replacement: [10 15 20 25 -1 -1 -1]


#### Array Operations

NumPy arrays support common operations as addition, subtraction and multiplication. These operations are performed element-wise, meaning that they are applied to each corresponding element in the arrays.

In [36]:
A = np.array(((1,2,3),
              (4,5,6)))
B = np.array(((10,20,30),
              (40,50,60)))

Element-wise addition, subtraction and multiplication can be performed with `+`, `-` and `*`. 

In [37]:
A + B

array([[11, 22, 33],
       [44, 55, 66]])

In [38]:
B - A

array([[ 9, 18, 27],
       [36, 45, 54]])

In [39]:
A * B

array([[ 10,  40,  90],
       [160, 250, 360]])

To multiply (`*`) or divide (`/`) all elements by an scalar, we just specify the scalar. 

In [40]:
A * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
B / 10

array([[1., 2., 3.],
       [4., 5., 6.]])

Note that NumPy automatically **broadcasts** the scalar to all elements of the array.

:::{.callout-tip}

### Broadcasting

Broadcasting is a powerful mechanism in NumPy that allows operations to be performed on arrays of different shapes. When performing operations between arrays of different shapes, NumPy automatically expands the smaller array along the dimensions of the larger array so that they have compatible shapes. This process is called broadcasting.

For example, consider adding a 1D array to a 2D array. NumPy will "broadcast" the 1D array across the rows of the 2D array to perform the addition.

In [42]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])  # 1D array
C = A + B  # B is broadcasted across the rows of A
print(C)

[[11 22 33]
 [14 25 36]]


:::


Comparing NumPy arrays is also possible using operators as `==`, `!=`, and the like. Comparisons will result in an array of booleans indicating if the condition is met for a given element. 

In [43]:
arr1 = np.array(((1,2,3),(4,5,6)))
arr2 = np.array(((1,5,3),(7,2,6)))
arr1==arr2

array([[ True, False,  True],
       [False, False,  True]])

Recall that we use double equals `==` for comparison, while a single equals `=` is used for assignment.


Note that element-wise multiplication is different from matrix multiplication. Matrix multiplication is achieved with either `@` or `matmul()`.

In [44]:
np.matmul(arr1,arr2.T) # Note the transpose of arr2 to match dimensions

array([[20, 29],
       [47, 74]])

In [45]:
arr1 @ arr2.T  # Note the transpose of arr2 to match dimensions

array([[20, 29],
       [47, 74]])

#### Exercises

1.  Create a 1D array with all integer elements from 1 to 10 (both included). No hard-coding allowed!
2.  From the array you created in 1, create one that contains all odd elements and one with all even elements. 
3.  Create a new array that replaces all elements in 1 that are odd by -1. 
4.  Create a 3-by-3 matrix filled with 'True' values (i.e., booleans).
5.  Suppose you have array `a=np.array(['a','b','c','d','e','f','g'])` and `b = np.array(['g','h','c','a','e','w','g'])`. Find all elements that are equal. Can you get the position where the elements of both arrays match?
6.  Write a function that takes a element an array and prints elements that are divisible by a given number. Try it creating an array from 1 to 20 and printing divisibles by 3.  
7. Consider two matrices, A and B, both of size 100x100, filled with random integer values between 1 and 10. Implement a function to perform element-wise multiplication of these matrices using nested loops. Implement the same operation using Numpy's vectorized multiplication. Repeat again with matrices of size 1000x1000, 10000x10000 and compare the execution time. Which one is faster? 